# Generated by Django 4.1.3 on 2022-12-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_startabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startabout',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
