# Generated by Django 4.1.3 on 2022-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_startabout_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Start team')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.DeleteModel(
            name='Startabout',
        ),
    ]
