# Generated by Django 4.1.3 on 2023-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
